/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculaPeso;

import javax.swing.JOptionPane;

/**
 *
 * @author Alexandre
 */
public class Peso extends javax.swing.JFrame {

    /**
     * Creates new form Peso
     */
    public Peso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoesDePlanetas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pesoNaTerra = new javax.swing.JTextField();
        planetaMercurio = new javax.swing.JRadioButton();
        planetaVenus = new javax.swing.JRadioButton();
        planetaMarte = new javax.swing.JRadioButton();
        planetaJupiter = new javax.swing.JRadioButton();
        planetaSaturno = new javax.swing.JRadioButton();
        planetaUrano = new javax.swing.JRadioButton();
        btnCalculaPeso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso na Terra");

        opcoesDePlanetas.add(planetaMercurio);
        planetaMercurio.setSelected(true);
        planetaMercurio.setText("Mercúrio");

        opcoesDePlanetas.add(planetaVenus);
        planetaVenus.setText("Vênus");

        opcoesDePlanetas.add(planetaMarte);
        planetaMarte.setText("Marte");

        opcoesDePlanetas.add(planetaJupiter);
        planetaJupiter.setText("Júpiter");

        opcoesDePlanetas.add(planetaSaturno);
        planetaSaturno.setText("Saturno");

        opcoesDePlanetas.add(planetaUrano);
        planetaUrano.setText("Urano");

        btnCalculaPeso.setText("Calcular Peso");
        btnCalculaPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaPesoActionPerformed(evt);
            }
        });

        jLabel2.setText("Ver o Peso em Qual Planeta?");

        btnSair.setBackground(java.awt.Color.red);
        btnSair.setForeground(java.awt.Color.white);
        btnSair.setText("X");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSair))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planetaMercurio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(planetaVenus)
                                .addGap(18, 18, 18)
                                .addComponent(planetaMarte))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(planetaJupiter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(planetaSaturno)
                                .addGap(18, 18, 18)
                                .addComponent(planetaUrano))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesoNaTerra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnCalculaPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnSair)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pesoNaTerra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planetaMercurio)
                    .addComponent(planetaVenus)
                    .addComponent(planetaMarte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planetaJupiter)
                    .addComponent(planetaSaturno)
                    .addComponent(planetaUrano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculaPeso)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculaPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaPesoActionPerformed
        int pesoNoPlaneta = Integer.parseInt(pesoNaTerra.getText());
        
        if (planetaMercurio.isSelected()) {
            pesoNoPlaneta *= .37;
        }
        
        if (planetaVenus.isSelected()) {
            pesoNoPlaneta *= .88;
        }
        
        if (planetaMarte.isSelected()) {
            pesoNoPlaneta *= .38;
        }
        
        if (planetaJupiter.isSelected()) {
            pesoNoPlaneta *= 2.64;
        }
        
        if (planetaSaturno.isSelected()) {
            pesoNoPlaneta *= 1.15;
        }
        
        if (planetaUrano.isSelected()) {
            pesoNoPlaneta *= 1.17;
        }
        
        JOptionPane.showMessageDialog(this, "Seu peso de " + pesoNaTerra.getText() + "kg na Terra equivale a " + pesoNoPlaneta + "kg no planeta escolhido");
    }//GEN-LAST:event_btnCalculaPesoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaPeso;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.ButtonGroup opcoesDePlanetas;
    private javax.swing.JTextField pesoNaTerra;
    private javax.swing.JRadioButton planetaJupiter;
    private javax.swing.JRadioButton planetaMarte;
    private javax.swing.JRadioButton planetaMercurio;
    private javax.swing.JRadioButton planetaSaturno;
    private javax.swing.JRadioButton planetaUrano;
    private javax.swing.JRadioButton planetaVenus;
    // End of variables declaration//GEN-END:variables
}
